defmodule Singularity.Storage.Crypto.Argon2PasswordHasher do
  @moduledoc """
  Versioned Argon2id credential hashing.

  Credential salts are generated by `Argon2` and are independent from every
  raw-key derivation salt.
  """

  @behaviour Singularity.Core.PasswordHasher

  alias Singularity.Core.Error

  @version 1
  @salt_length 16
  @hash_length 32
  @verifier_pattern ~r/\A\$argon2id\$v=19\$m=(\d+),t=(\d+),p=(\d+)\$([A-Za-z0-9+\/]+)\$([A-Za-z0-9+\/]+)\z/

  @impl true
  def hash(params, password) when is_binary(password) and byte_size(password) > 0 do
    with {:ok, options} <- options(params) do
      {:ok, Argon2.hash_pwd_salt(password, options)}
    end
  rescue
    ArgumentError -> {:error, Error.new(:invalid)}
  end

  def hash(_params, _password), do: {:error, Error.new(:invalid)}

  @impl true
  def verify(params, password, verifier)
      when is_binary(password) and is_binary(verifier) do
    with {:ok, _options} <- options(params),
         :ok <- validate_verifier_policy(verifier, params) do
      {:ok, Argon2.verify_pass(password, verifier)}
    end
  rescue
    ArgumentError -> {:error, Error.new(:invalid)}
  end

  def verify(_params, _password, _verifier),
    do: {:error, Error.new(:invalid)}

  defp options(%{
         version: @version,
         t_cost: t_cost,
         m_cost: m_cost,
         parallelism: parallelism
       })
       when is_integer(t_cost) and t_cost > 0 and is_integer(m_cost) and
              m_cost >= 8 and is_integer(parallelism) and parallelism > 0 do
    {:ok,
     [
       t_cost: t_cost,
       m_cost: m_cost,
       parallelism: parallelism,
       argon2_type: 2,
       salt_len: @salt_length,
       hashlen: @hash_length
     ]}
  end

  defp options(_params), do: {:error, Error.new(:invalid)}

  defp validate_verifier_policy(
         verifier,
         %{
           version: @version,
           t_cost: expected_t_cost,
           m_cost: expected_m_cost,
           parallelism: expected_parallelism
         }
       )
       when byte_size(verifier) <= 512 do
    with [memory, time, parallelism, salt, hash] <-
           Regex.run(@verifier_pattern, verifier, capture: :all_but_first),
         {memory, ""} <- Integer.parse(memory),
         {time, ""} <- Integer.parse(time),
         {parallelism, ""} <- Integer.parse(parallelism),
         {:ok, salt} <- Base.decode64(salt, padding: false),
         {:ok, hash} <- Base.decode64(hash, padding: false),
         true <- memory == :erlang.bsl(1, expected_m_cost),
         true <- time == expected_t_cost,
         true <- parallelism == expected_parallelism,
         true <- byte_size(salt) == @salt_length,
         true <- byte_size(hash) == @hash_length do
      :ok
    else
      _invalid -> {:error, Error.new(:invalid)}
    end
  end

  defp validate_verifier_policy(_verifier, _params),
    do: {:error, Error.new(:invalid)}
end
